import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "ChefBuddy",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Fixed Navbar - top-0 ensure kore eta upore thakbe */}
          <header className=" z-50 w-full">
            <Navbar />
          </header>

          {/* Main Content - flex-grow ensure kore eta baki jayga nibe */}
          <main className="flex-grow">
            {children}
          </main>

          {/* Footer - niche thakbe */}
          <Footer />
        </div>
      </body>
    </html>
  );
}